#image: node:10.15.3

variables:
  VERSION_ID: '0.9.0'

before_script:
  - node -v

stages:
  - build

cache:
  paths:
    - node_modules/

build:
#  image: slauta93/electron-builder-win
  image: node:10.15.3
  stage: build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist/*.*
  script:
    - if [ -f /.dockerenv ]; then echo "docker-executor"; fi
    - sed "s/0.0.0/${VERSION_ID}/g" package.json > _package.json && mv _package.json package.json
    - npm install && CI=false npm run build