stages:
  - test
  - build
  - deploy

test-app:
  stage: test
  image: node:lts-alpine
  script:
    - npm install
    - npm run test:colors

electron-release-build:
  only:
    - master
  stage: build
  image: electronuserland/builder:wine
  script:
    - npm ci
    - npm run package:publish
  artifacts:
    paths:
      - electron-release/*.exe*
      - electron-release/*.yml
    expire_in: 1 month

pages:
  stage: deploy
  only:
    - master
  image: alpine:latest
  dependencies:
    - electron-release-build
  script:
    # Note that `public` already exists in this repo, and has an index.html to
    # to act as a downloads page.
    - cp electron-release/*.exe electron-release/*.blockmap electron-release/*.yml public
    - EXE_FILENAME=$(find ./electron-release -maxdepth 1 -name "Solvergy-Systems*.exe")
    - EXE_BASENAME=$(basename "$EXE_FILENAME")
    - sed -i "s/INSERT_FILE_NAME/${EXE_BASENAME}/g" ./public/index.html
  artifacts:
    paths:
      - public
